<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>P3FesPnachPatcher</AssemblyName>
    <RootNamespace>P3FesPnachPatcher</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationIcon Condition="Exists('icon.ico')">icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
  </ItemGroup>

</Project>
